version: "3"
services:

  traefik:
    container_name: "traefik"
    image: "traefik:1.7.16"
    restart: "unless-stopped"
    ports:
      - "8080:8080"
      - "81:80"
    expose:
      - "8080"
      - "81"
      - "443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./infrastructure/traefik.toml:/traefik.toml"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "75:80"
    labels:
      traefik.enable: "true"
      traefik.backend: "frontend-server"
      traefik.port: 80
      traefik.frontend.rule: "PathPrefix:/"
      traefik.frontend.priority: 1

  api:
    image: ${DOCKER_REGISTRY-}apiserver
    build:
      context: api
      dockerfile: ApiServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DATABASE_LOCATION=/storage/Database.db
    ports:
      - "76:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./api/ApiServer/storage:/storage

    labels:
      traefik.enable: "true"
      traefik.backend: "api-server"
      traefik.port: 80
      traefik.frontend.rule: "PathPrefixStrip:/api"
      traefik.frontend.priority: 2
