export const mockedResponse = {
    "collection": [
        {
        "brand": "Ariston",
        "modelName": "Matis condens",
        "available": true,
        "type": "Condensing",
        "wattPower": 24,
        "poweredBy": "Methane",
        "usage": "Indoor",
        "price": 1350,
        "includes": "Sopralluogo e installazione inclusi",
        "promo": true,
        "discountDisclaimer": "Risparmi il 20%",
        "oldPrice": 1570,
        "rating": 4,
        "id": 1
        },
        {
        "brand": "Ariston",
        "modelName": "Genus One Condensig Boiler",
        "available": true,
        "type": null,
        "wattPower": 24,
        "poweredBy": null,
        "usage": null,
        "price": 899,
        "includes": "Sopralluogo e installazione inclusi",
        "promo": true,
        "discountDisclaimer": "Risparmi il 20%",
        "oldPrice": 927,
        "rating": 4,
        "id": 2
        },
        {
        "brand": "Baxi",
        "modelName": "Luna Duo-Tec Condensing Boiler",
        "available": true,
        "type": null,
        "wattPower": 28,
        "poweredBy": null,
        "usage": null,
        "price": 790,
        "includes": "Sopralluogo e installazione inclusi",
        "promo": false,
        "discountDisclaimer": null,
        "oldPrice": null,
        "rating": 4,
        "id": 3
        },
        {
        "brand": "Baxi",
        "modelName": "Genus One Condensing Boiler",
        "available": true,
        "type": null,
        "wattPower": 24,
        "poweredBy": null,
        "usage": null,
        "price": 960,
        "includes": "Sopralluogo e installazione inclusi",
        "promo": false,
        "discountDisclaimer": null,
        "oldPrice": null,
        "rating": 4,
        "id": 4
        },
        {
        "brand": "Baxi",
        "modelName": "Prime Condensing Boiler",
        "available": true,
        "type": null,
        "wattPower": 28,
        "poweredBy": null,
        "usage": null,
        "price": 890,
        "includes": "Sopralluogo e installazione inclusi",
        "promo": false,
        "discountDisclaimer": null,
        "oldPrice": null,
        "rating": 4,
        "id": 5
        },
        {
        "brand": "Ariston",
        "modelName": "Matis condens",
        "available": true,
        "type": "Condensing",
        "wattPower": 24,
        "poweredBy": "Methane",
        "usage": "Indoor",
        "price": 1120,
        "includes": "Sopralluogo e installazione inclusi",
        "promo": false,
        "discountDisclaimer": null,
        "oldPrice": null,
        "rating": 4,
        "id": 6
        },
        {
        "brand": "Baxi",
        "modelName": "Luna Duo-Tec Condensing Boiler",
        "available": true,
        "type": null,
        "wattPower": 28,
        "poweredBy": null,
        "usage": null,
        "price": 790,
        "includes": "Sopralluogo e installazione inclusi",
        "promo": true,
        "discountDisclaimer": "Rispamia il 16%",
        "oldPrice": 927,
        "rating": 4,
        "id": 7
        },
        {
        "brand": "Baxi",
        "modelName": "Genus One Condensing Boiler",
        "available": true,
        "type": null,
        "wattPower": 24,
        "poweredBy": null,
        "usage": null,
        "price": 960,
        "includes": "Sopralluogo e installazione inclusi",
        "promo": false,
        "discountDisclaimer": null,
        "oldPrice": null,
        "rating": 4,
        "id": 8
        },
        {
        "brand": "Ariston",
        "modelName": "Genus One Condensing Boiler",
        "available": true,
        "type": null,
        "wattPower": 24,
        "poweredBy": null,
        "usage": null,
        "price": 899,
        "includes": "Sopralluogo e installazione inclusi",
        "promo": true,
        "discountDisclaimer": "Risparmi il 20%",
        "oldPrice": 927,
        "rating": 4,
        "id": 9
        },
        {
        "brand": "Baxi",
        "modelName": "Genus One Condensing Boiler",
        "available": true,
        "type": "Condensing",
        "wattPower": 24,
        "poweredBy": null,
        "usage": null,
        "price": 960,
        "includes": "Sopralluogo e installazione inclusi",
        "promo": false,
        "discountDisclaimer": null,
        "oldPrice": null,
        "rating": 4,
        "id": 10
        },
        {
        "brand": "Ariston",
        "modelName": "Matis condens",
        "available": true,
        "type": "Condensing",
        "wattPower": 24,
        "poweredBy": "Methane",
        "usage": "Indoor",
        "price": 1120,
        "includes": "Sopralluogo e installazione inclusi",
        "promo": false,
        "discountDisclaimer": null,
        "oldPrice": null,
        "rating": 4,
        "id": 11
        },
        {
        "brand": "Baxi",
        "modelName": "Prime Condensing Boiler",
        "available": true,
        "type": null,
        "wattPower": 28,
        "poweredBy": null,
        "usage": null,
        "price": 890,
        "includes": "Sopralluogo e installazione inclusi",
        "promo": false,
        "discountDisclaimer": null,
        "oldPrice": null,
        "rating": 4,
        "id": 12
        }
    ],
    "offset": null,
    "limit": null,
    "size": 12
};